### ISSUE TITLE
RadiusQuery issue

### ISSUE THREAD

**Issue by kiririn39** [bazhenovc/SpatialIndex#1]
Hi. 
First of all, thank you for the project. It helped me a lot.

Now, to the point of this discussion.
In radius query, example code get radius in tiles as follows
`const i32 radiusInTiles = i32(std::ceilf(radius) / f32(tileSize))`

I can't completely understand how this supposed to work.
I've tried anything, but my query can't detect large items that are in adjacent blocks in case of small input radius, e.g when resulting radius in tiles == 0.

`const i32 radiusInTiles = i32(std::ceilf(radius) / f32(tileSize)) + 1;`
If I were to make my Query always more than 1 everything starts t work.

Second issue, maybe not an issue just a small note. i
`for (i32 tileX = (queryTileX - radiusInTiles); tileX <= (queryTileX + radiusInTiles); tileX++)`
f queryTileX or queryTileY end up being 0, loops start from -1, which, in my case also led to broken logic.

Got them fixed the same way
```
const i32 queryTileX = std::max(i32(std::floorf(position.x) / f32(tileSize)), 1);
const i32 queryTileY = std::max(i32(std::floorf(position.y) / f32(tileSize)), 1);
```

**Comment by bazhenovc** [comment]
Hi, I'm glad that you found this code useful!

I think you have a bug in your code:

`const i32 radiusInTiles = i32(std::ceilf(radius) / f32(tileSize))` 

You are ceiling the radius here, instead you should be ceiling the result of dividing the radius by float tile size. I believe that once you've fixed that you don't really need the other changes. It should look like this:

`const int radius_in_tiles = int(std::ceilf(radius / float(tile_size)));`

EDIT: Same issue with flooring the positions, you need to floor the result of division by float tile size.

**Comment by kiririn39** [comment]
Hi, thanks for reply. 

I tried flooring \ ceiling the result of division but that didn't change much for me. 

To be clear, my std::max to 1 and yours example are both working, it's only issue of a performance here. 
I would like to try out your code from this repository wit my changes, but it doesn't have all dependent projects so I can't build it

**Comment by bazhenovc** [comment]
You should be able to build it, you need to right click on the solution and press "restore nuget packages" - this will download dependencies and it should build after that. You don't need to download anything manually.

I'm curious to see the performance difference with your changes, feel free to post your results here.

**Comment by kiririn39** [comment]
Well, turns out I was wrong. 
For some reason this change slows down particles simulation by ~2ms on average, but for me, in my workload, it was speeding up for quite a lot. Guess I have a bit different workload or some kind of error in my program, probably the latter.

Anyways, thanks for spending time on me, closing this issue
